### ISSUE TITLE
Cancelling the facebook permissions request causes 500 error

### ISSUE THREAD

**Issue by fridaystreet** [stefanbuck/sails-social-auth-example#31]
Hi,

If I cancel the facebook permissions request I just get redirected back to the callback url with a 500 error. Same is true if you have the display as 'popup' and you cancel the facebook login popup.

Cheers
Paul

**Comment by stefanbuck** [comment]
Hi @fridaystreet,

this is just a demo implementation with a limited functionality. If have an idea how this could be done, feel free to sent a PR.
