### ISSUE TITLE
Getting username from the req.user

### ISSUE THREAD

**Issue by prem-kumar-e** [stefanbuck/sails-social-auth-example#32]
How do i get the username and other details of the logged in user. Now I am getting only the below by using "req.user"
{
email: 'xxxr@xyx.com',
createdAt: '2015-08-12T10:47:25.404Z',
updatedAt: '2015-08-12T10:47:25.405Z',
id: '55cb243d8bbd86d5237c2f7f' 
}

**Comment by stefanbuck** [comment]
You have to use the user model like this

``` js
User.findOne({uid:  '55cb243d8bbd86d5237c2f7f'}, function(err, user) {
   console.log(user.username)
});
```
