### ISSUE TITLE
Errors for missing policies in api/policies/

### ISSUE THREAD

**Issue by csuwildcat** [stefanbuck/sails-social-auth-example#33]
Immediately on start the console complains that the policies for `basicAuth` and `passport` are non-existant, and neither are in the `api/policies/` dir as the command line describes.

**Comment by stefanbuck** [comment]
Sorry for the daily. This repo is a bit outdated and not well maintain from my side. I guess this is the root cause for this warning. A PR is welcome to get rid of the warning.
